language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
install: pip install -U -r requirements-dev.txt
dist: bionic
os: linux
script: python -m pytest --tb=short --durations=5 --cov-report=term --cov=mnamer
after_success:
  - codecov
