[pytest]
addopts = --tb=short
filterwarnings =
    ignore:Transitional processing has been removed from UTS #46.*:DeprecationWarning:url_normalize\.normalize_host

markers =
    e2e
    local
    network
    omdb
    tmdb
    tvdb
    tvmaze
