name: Lint
description: Lints the codebase with ruff and mypy

inputs:
  ruff:
    description: Whether to run ruff
    required: false
    default: "true"

  mypy:
    description: Whether to run mypy
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Linting with ruff
      if: inputs.ruff == 'true'
      run: uv run ruff check mnamer tests
      shell: sh

    - name: Formatting with ruff
      if: inputs.ruff == 'true'
      run: uv run ruff format --check mnamer tests
      shell: sh

    - name: Type checking with mypy
      if: inputs.mypy == 'true'
      run: uv run mypy mnamer tests
      shell: sh
