name: Init
description: Sets up the environment for build, lint, and test jobs

inputs:
  save-cache:
    description: Whether to save the uv cache after the job
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v6.2.0
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        enable-cache: true
        save-cache: ${{ inputs.save-cache }}
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock

    - name: Install dependencies
      shell: sh
      run: uv sync --python 3.12 --locked --dev
