name: publish

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish-pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 } # required for setuptools_scm to detect git tags
      - uses: ./.github/actions/init

      - name: Building
        run: uv build

      - name: Reporting Version
        run: uv run python -m mnamer --version

      - name: Uploading to PyPI
        run: uv publish --token ${{secrets.pypi_password}}
