name: pr

on: pull_request

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/init
        with:
          save-cache: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      - uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/init
        with:
          save-cache: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      - uses: ./.github/actions/test
