name: pr

on: pull_request

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/init
        with:
          save-cache: ${{ github.event.pull_request.head.repo.full_name == github.repository }}

      - name: Linting
        uses: ./.github/actions/lint
        with:
          ruff: true
          mypy: true

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/init
        with:
          save-cache: ${{ github.event.pull_request.head.repo.full_name == github.repository }}

      - name: Testing (PR)
        uses: ./.github/actions/test
        with:
          local: true
          network: false
          e2e: false
          coverage: false
