name: push

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * 1" # mondays at 8am
  release:
    types:
      - published
      - prereleased

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/init
      - uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/init
      - name: Testing
        uses: ./.github/actions/test
        env:
          API_KEY_OMDB: ${{ secrets.API_KEY_OMDB }}
        with:
          local: true
          network: ${{ github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
          e2e: ${{ github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
          coverage: true
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  publish-pypi:
    if: >-
      success()
      && github.event_name == 'push'
      && github.ref == 'refs/heads/main'

    needs:
      - lint
      - test

    secrets:
      inherit

    uses: ./.github/workflows/publish.yml

  publish-docker-main:
    if: >-
      success()
      && github.event_name == 'push'
      && github.ref == 'refs/heads/main'

    needs:
      - lint
      - test

    secrets:
      inherit

    uses: ./.github/workflows/publish-docker.yml
    with:
      target: latest-sha

  publish-docker-release:
    if: >-
      success()
      && github.event_name == 'release'
      && (
        github.event.action == 'published'
        || github.event.action == 'prereleased'
      )

    needs:
      - lint
      - test

    secrets:
      inherit

    uses: ./.github/workflows/publish-docker.yml
    with:
      target: event-release
      release_tag: ${{ github.event.release.tag_name }}
      is_prerelease: ${{ github.event.release.prerelease }}
